{% set name = "pandas" %}
{% set version = "0.23.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pandas-dev/pandas/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe9946df55e1208cb59a273862cd38520c8e4468b6bb88372b215881eef9e91c

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - cython
    - numpy 1.9.*  # [py27 or py35]
    - numpy 1.11.*  # [py36]
  run:
    - python
    - numpy >=1.9.*  # [py27 or py35]
    - numpy >=1.11.*  # [py36]
    - python-dateutil >=2.5.0
    - pytz

test:
  imports:
    - pandas
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://pandas.pydata.org
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-performance, easy-to-use data structures and data analysis tools.'

extra:
  recipe-maintainers:
    - jreback
    - jorisvandenbossche
    - msarahan
    - ocefpaf
    - TomAugspurger
