travis:
  secure:
    BINSTAR_TOKEN: cugmF35AdRWm6rZvPQHs0U3oX5CJCTxhp8K9m5EUxSPBjuzJZRAfXuKxUZtP+Kg+qoeYAr7F4mwWDGwEpcrfHHH7LS+y2DFAU+u2gCJJqYuSG4Ya/edis3OJPv/1SFfSqYsRRiu0NMZygX/p2tUHj0d5nwxuKMc5YMML6xdE/Ta7Z6Mmx7+X91NiRRUNXQTkLpwpuBvXD5ztmLdlx2u/imsNR9DVs0AhKXzSBbITqwoh9o48c9NqYm14Q7k1DKYvhX6AC3Y/sKYqHAZa8nrO4t3ETayQTn0fETd8XdSQdpBrwELbhwBu6Yawx9kt2uwVlZ5g9lNu106Uw+t1bffEQCsiddgETPWfvRnHfeJBZpqe8PpOtIE2yh5PyEvQ7YokMB46vAdi5GgnkXMVBGy6VkjIFFonKsjoHN+ogdnbOrNmO4gmEFkIvuPs9JHXbxvd5d5cALrG9SU1zgoMjpotj2PHu7yCjEXdPSGNL0KhbB93zj80g8RS8Dp1Uclub/KBjta0pcW1iIZgNjRT+s3Q4TOPOC/rCuuoxyNePoMvO+akbEt8WfNYTtegL1iO3xEtZmCCPe1thUWU9rM5/JXcBP/Udx1mudl4Gjui3eOcgXXWPdNZNJoqLb3z17vTtkNw887Y/RAMmjcwLyuOepPpdUshvtl80zKBjDNRtxkqrnw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
channels:
    targets:
        - [conda-forge, rc]
