appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c344237302eb707003cf850
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: suoo9AIX+/Nc0pCKrwvCQqBy0kHqA5EZzdqPj3B0HT1LJJ4uTbzkdQzN2BRgVGDpFFCORkSjY6os2ioGgqjiljxIWdM2QA8gGGsQiTYoedJKndBoTVxXaW8idaDIlOTOmQMHgUDOqCVxc4Q/5cpZefVAt3pwWcUSuERsVdwX/NP3oukdxBtRe8WLN32Nil2oN+sY85oHL8QC8RyMq0DXrWh39kRfZFuhdFDD2TmTuqHryUz4fl7TMiA0OVOa58wBjCZQeBEjYQSllsyLzj7HtpuikT7gtPlk/Crx7h2EkFAHtSSXPww9IaknBksnhr/JfmJfnurafBrTqq9U6pffJtnWK14T/15K+dhjy4pS1f09pEsILgQLf3HVzn6816yYN6XAvADe1uJNLSdtibtBI/WyV3XA7JVJQmTx/wb6cjGteC0QQFhZTYSGtRBSSyqWW95yiqNUdsMgJsmelKKR6UsQ1h4hpdTdm6MT/Qm4cGYfSzqeqCLWY6LecgpainWuD2wmiyLEbltbnMZ1+Ipb/EXqBCMF45dXox/MvDNM4hvOpm2LfZim3rnZPDpQ1749tVXxc9DVZjsTrY0NzJYdTxy5ijYr7mzXTYX/8v8TDJ4VSQUF9RfN9qYmJ7DSO8VoTNnPaSc8IR7/qNC/ky/pJHOpFVFJozY9+O1JHBa3zLQ=}
